"""
CsiNet_train.py
Complete Training Script for Exercise 2.15 (CsiNet Generalization)

This script trains a CsiNet autoencoder to compress and reconstruct 
Channel State Information (CSI) matrices. It supports training on a 
single dataset to observe generalization failure (Task B), and mixed 
training across multiple datasets to improve robustness (Task C).
"""

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Reshape, Conv2D, Add, LeakyReLU
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import TensorBoard, Callback
import scipy.io as sio 
import numpy as np
import time
import os

# ────────────────────────  Configuration  ───────────────────────── #
# Exercise 2.15 Mode Selection:
# 'B' = Train on a single dataset (to evaluate generalization vulnerability)
# 'C' = Train on a mixture of all 6 datasets (to enhance generalization/robustness)
TASK_MODE = 'C' 
DATASET_ID = 1  # If TASK_MODE is 'B', this dictates which dataset to train on

# CSI Image Parameters
img_height = 32        # Number of Base Station (BS) antennas to extract
img_width = 32         # Number of subcarriers (frequency bins) to extract
img_channels = 2       # Represents the Real and Imaginary components of the complex CSI
img_total = img_height * img_width * img_channels # Total flattened dimensions (2048)

# Network Hyperparameters
residual_num = 2       # Number of residual blocks used in the decoder
encoded_dim = 512      # Compression dimension (Latent space size). 512 corresponds to a 1/4 compression ratio

# Ensure necessary output directories exist
os.makedirs('result', exist_ok=True)
os.makedirs('data', exist_ok=True)

# ────────────────────────  Data Preprocessing Function ──────────────────── #
def load_and_preprocess_mat(dataset_idx):
    """
    Loads a .mat file generated by MATLAB (COST2100 model) and reshapes it 
    into the format required by the CsiNet neural network.
    
    Args:
        dataset_idx (int): The ID of the dataset to load (1 to 6).
    Returns:
        np.array: Preprocessed CSI data of shape [Samples, 2, 32, 32]
    """
    print(f"Loading data/channel_dataset_{dataset_idx}.mat ...")
    mat = sio.loadmat(f'data/channel_dataset_{dataset_idx}.mat')
    
    # Raw MATLAB output shape: [snapshots, freq_bins, users, bs_antennas]
    H_raw = mat['H_transfer'] 
    
    # Truncate the matrix to use only the first 32 subcarriers and first 32 antennas
    H_sliced = H_raw[:, :img_width, :, :img_height] 
    
    # Transpose and reshape the matrix to merge 'snapshots' and 'users' into a single 'Samples' dimension
    # Resulting shape: [Total_Samples, freq_bins, bs_antennas]
    H_samples = np.transpose(H_sliced, (0, 2, 1, 3)).reshape(-1, img_width, img_height)
    
    # CsiNet requires channels-first format: [Samples, Channels, Height, Width]
    # We split the complex numbers into separate Real (channel 0) and Imaginary (channel 1) parts
    x_data = np.zeros((H_samples.shape[0], img_channels, img_height, img_width), dtype=np.float32)
    x_data[:, 0, :, :] = np.real(H_samples)
    x_data[:, 1, :, :] = np.imag(H_samples)
    
    return x_data

# ────────────────────────  Load Data based on Task  ─────────────────────── #
if TASK_MODE == 'B':
    print(f"--- Running Task (b): Training on Dataset {DATASET_ID} only ---")
    x_data = load_and_preprocess_mat(DATASET_ID)
elif TASK_MODE == 'C':
    print("--- Running Task (c): Mixed Training on Datasets 1 to 6 ---")
    # Load all 6 datasets and concatenate them along the sample axis (axis=0)
    data_list = [load_and_preprocess_mat(i) for i in range(1, 7)]
    x_data = np.concatenate(data_list, axis=0)
else:
    raise ValueError("TASK_MODE must be either 'B' or 'C'")

# Data Normalization
# Neural networks (especially those with a Sigmoid layer) perform best with inputs in the [0, 1] range.
# We divide by the global absolute maximum to map data to [-0.5, 0.5], then add 0.5 to shift to [0, 1].
max_abs = np.max(np.abs(x_data))
x_norm = (x_data / max_abs) * 0.5 + 0.5

# Save the normalization factor (max_abs). 
# We need it during the inference phase to denormalize the predictions back to their original physical scale before calculating the NMSE.
model_name = f'CsiNet_Task{TASK_MODE}_dim{encoded_dim}'
np.save(f'result/{model_name}_max_abs.npy', max_abs)

# Data Splitting: 80% for Training, 20% for Validation
np.random.seed(42) # Set seed for reproducibility
np.random.shuffle(x_norm) # Shuffle the dataset to avoid ordering biases
split_idx = int(len(x_norm) * 0.8)
x_train, x_val = x_norm[:split_idx], x_norm[split_idx:]

print(f"Total training samples: {len(x_train)}")
print(f"Total validation samples: {len(x_val)}")

# ────────────────────────  CsiNet Architecture  ─────────────────────────── #
def residual_network(x, residual_num, encoded_dim):
    """
    Builds the CsiNet autoencoder using Keras functional API.
    Architecture includes a convolutional encoder, a dense bottleneck, 
    and a decoder augmented with residual blocks.
    """
    def add_common_layers(y):
        """Helper block: Batch Normalization followed by LeakyReLU activation."""
        y = BatchNormalization()(y)
        y = LeakyReLU()(y)
        return y

    def residual_block_decoded(y):
        """
        Defines a single Residual Block for the decoder.
        It uses a skip connection (shortcut) to mitigate the vanishing gradient problem.
        """
        shortcut = y
        # 1st Conv Layer
        y = Conv2D(8, kernel_size=(3, 3), padding='same', data_format='channels_first')(y)
        y = add_common_layers(y)
        # 2nd Conv Layer
        y = Conv2D(16, kernel_size=(3, 3), padding='same', data_format='channels_first')(y)
        y = add_common_layers(y)
        # 3rd Conv Layer (Shrinks back to 2 channels to match input dimensions)
        y = Conv2D(2, kernel_size=(3, 3), padding='same', data_format='channels_first')(y)
        y = BatchNormalization()(y)
        
        # Element-wise addition of the input (shortcut) and the output of the convolutional block
        y = Add()([shortcut, y]) # Keras TF2 syntax
        y = LeakyReLU()(y)
        return y
    
    # --- ENCODER ---
    # Initial feature extraction convolution
    x = Conv2D(2, (3, 3), padding='same', data_format="channels_first")(x)
    x = add_common_layers(x)
    
    # Flatten the 3D tensor to a 1D vector and compress it to the bottleneck dimension
    x = Reshape((img_total,))(x)
    encoded = Dense(encoded_dim, activation='linear')(x) # The compressed codeword
    
    # --- DECODER ---
    # Decompress back to the original flattened size
    x = Dense(img_total, activation='linear')(encoded)
    x = Reshape((img_channels, img_height, img_width))(x)
    
    # Pass through the residual blocks to refine the spatial/frequency reconstruction
    for i in range(residual_num):
        x = residual_block_decoded(x)
        
    # Final Convolutional layer with a Sigmoid activation to ensure outputs strictly fall in [0, 1]
    x = Conv2D(2, (3, 3), activation='sigmoid', padding='same', data_format="channels_first")(x)
    return x

# Build and compile the Keras Model
image_tensor = Input(shape=(img_channels, img_height, img_width))
network_output = residual_network(image_tensor, residual_num, encoded_dim)
autoencoder = Model(inputs=[image_tensor], outputs=[network_output])

# Compile using Adam optimizer and Mean Squared Error (MSE) loss function
autoencoder.compile(optimizer='adam', loss='mse')

# ────────────────────────  Model Training ───────────────────────────────── #
class LossHistory(Callback):
    """Custom Keras callback to record batch-level and epoch-level losses."""
    def on_train_begin(self, logs={}):
        self.losses_train = []
        self.losses_val = []
    def on_batch_end(self, batch, logs={}):
        self.losses_train.append(logs.get('loss'))
    def on_epoch_end(self, epoch, logs={}):
        self.losses_val.append(logs.get('val_loss'))
        
history = LossHistory()
tb_path = f'result/TensorBoard_{model_name}'

print("\nStarting Training...")
autoencoder.fit(
    x_train, x_train, # Autoencoder target is the input itself
    epochs=1000,      # Number of passes over the entire dataset (adjust based on hardware capabilities)
    batch_size=128,   # Number of samples per gradient update
    shuffle=True,     # Shuffle training data each epoch
    validation_data=(x_val, x_val),
    callbacks=[history, TensorBoard(log_dir=tb_path)] # Track metrics
)

# ────────────────────────  Save Model ───────────────────────────────────── #
# Serialize network architecture to JSON format
with open(f"result/model_{model_name}.json", "w") as json_file:
    json_file.write(autoencoder.to_json())

# Serialize network weights to HDF5 format
autoencoder.save_weights(f"result/model_{model_name}.weights.h5")
print(f"Model successfully saved as: {model_name}")